/**
 * Données fictives pour la démo Seedow — "Le Jardin".
 * Pas de backend : on simule un jardin déjà bien planté.
 */

export interface MockAsset {
  id: string;
  ticker: string;
  name: string;
  category: string;
  description: string;
  current_price: number;
  overall_esg_score: number;
  climate_score: number;
  social_score: number;
  governance_score: number;
  tags: string[];
  co2_factor_per_1k_eur: number;
  energy_factor_per_1k_eur: number;
  themes: string[]; // matche lexicon.themes
  // — Détails complémentaires pour aider l'investisseur à comprendre
  issuer?: string;            // émetteur / société de gestion
  domicile?: string;          // pays de domiciliation (ex: Irlande)
  currency?: string;          // devise de cotation
  ter_pct?: number;           // frais courants annuels (%)
  dividend_policy?: "Capitalisant" | "Distribuant";
  dividend_yield_pct?: number;
  holdings_count?: number;    // nombre de lignes (pour ETF)
  top_holdings?: string[];    // top positions (pour ETF/fonds)
  sector_breakdown?: { label: string; pct: number }[];
  geo_breakdown?: { label: string; pct: number }[];
  risk_level?: 1 | 2 | 3 | 4 | 5 | 6 | 7; // SRRI 1-7
  inception_year?: number;
  benchmark?: string;
  exclusions?: string[];      // secteurs exclus
}

export interface MockHolding {
  id: string;
  asset: MockAsset;
  allocationPct: number;
  performancePct: number;
  avgBuyPrice: number;
}

export interface MockTransaction {
  id: string;
  created_at: string; // ISO
  type: "buy" | "sell" | "deposit" | "withdrawal";
  asset_ticker: string | null;
  asset_name: string | null;
  amount: number;
}

export const MOCK_ASSETS: MockAsset[] = [
  {
    id: "a-iwrd",
    ticker: "IWRD",
    name: "iShares Core MSCI World",
    category: "ETF",
    description:
      "Un bouquet de 1 500 entreprises mondiales filtrées sur des critères ESG stricts. Une graine robuste pour démarrer.",
    current_price: 92.4,
    overall_esg_score: 8.1,
    climate_score: 7.8,
    social_score: 8.2,
    governance_score: 8.4,
    tags: ["diversifié", "monde", "ESG"],
    co2_factor_per_1k_eur: 0.35,
    energy_factor_per_1k_eur: 180,
    themes: ["climat", "governance"],
    issuer: "BlackRock iShares",
    domicile: "Irlande",
    currency: "USD",
    ter_pct: 0.20,
    dividend_policy: "Capitalisant",
    holdings_count: 1512,
    top_holdings: ["Apple", "Microsoft", "Nvidia", "Alphabet", "Amazon"],
    sector_breakdown: [
      { label: "Tech", pct: 24 },
      { label: "Finance", pct: 16 },
      { label: "Santé", pct: 13 },
      { label: "Conso.", pct: 12 },
      { label: "Industrie", pct: 11 },
      { label: "Autres", pct: 24 },
    ],
    geo_breakdown: [
      { label: "USA", pct: 68 },
      { label: "Europe", pct: 16 },
      { label: "Japon", pct: 6 },
      { label: "Autres", pct: 10 },
    ],
    risk_level: 5,
    inception_year: 2009,
    benchmark: "MSCI World",
    exclusions: ["Armes controversées", "Tabac", "Charbon thermique"],
  },
  {
    id: "a-clean",
    ticker: "CLEAN",
    name: "iShares Global Clean Energy",
    category: "ETF",
    description:
      "100 % énergies renouvelables : solaire, éolien, hydrogène. Le moteur de la transition énergétique mondiale.",
    current_price: 14.8,
    overall_esg_score: 9.2,
    climate_score: 9.7,
    social_score: 8.4,
    governance_score: 8.6,
    tags: ["climat", "renouvelable"],
    co2_factor_per_1k_eur: 1.2,
    energy_factor_per_1k_eur: 450,
    themes: ["climat", "tech"],
    issuer: "BlackRock iShares",
    domicile: "Irlande",
    currency: "USD",
    ter_pct: 0.65,
    dividend_policy: "Distribuant",
    dividend_yield_pct: 1.2,
    holdings_count: 100,
    top_holdings: ["First Solar", "Enphase Energy", "Vestas Wind", "Iberdrola", "Plug Power"],
    sector_breakdown: [
      { label: "Solaire", pct: 38 },
      { label: "Éolien", pct: 28 },
      { label: "Réseaux", pct: 14 },
      { label: "Hydrogène", pct: 10 },
      { label: "Autres", pct: 10 },
    ],
    geo_breakdown: [
      { label: "USA", pct: 42 },
      { label: "Europe", pct: 30 },
      { label: "Asie", pct: 22 },
      { label: "Autres", pct: 6 },
    ],
    risk_level: 6,
    inception_year: 2007,
    benchmark: "S&P Global Clean Energy",
    exclusions: ["Énergies fossiles", "Nucléaire"],
  },
  {
    id: "a-grnb",
    ticker: "GRNB",
    name: "VanEck Green Bond",
    category: "Obligation",
    description:
      "Obligations vertes qui financent des projets environnementaux concrets : reforestation, mobilité propre, eau.",
    current_price: 24.6,
    overall_esg_score: 8.7,
    climate_score: 9.0,
    social_score: 8.0,
    governance_score: 8.9,
    tags: ["obligation", "stable"],
    co2_factor_per_1k_eur: 0.8,
    energy_factor_per_1k_eur: 220,
    themes: ["climat", "biodiversite"],
    issuer: "VanEck",
    domicile: "Irlande",
    currency: "EUR",
    ter_pct: 0.35,
    dividend_policy: "Distribuant",
    dividend_yield_pct: 3.4,
    holdings_count: 380,
    top_holdings: ["Banque Européenne d'Investissement", "KfW", "France OAT verte", "Allemagne Bund vert", "Banque mondiale"],
    sector_breakdown: [
      { label: "Énergie verte", pct: 36 },
      { label: "Bâtiment durable", pct: 22 },
      { label: "Transport propre", pct: 18 },
      { label: "Eau", pct: 12 },
      { label: "Autres", pct: 12 },
    ],
    geo_breakdown: [
      { label: "Europe", pct: 56 },
      { label: "USA", pct: 18 },
      { label: "Asie", pct: 18 },
      { label: "Autres", pct: 8 },
    ],
    risk_level: 3,
    inception_year: 2017,
    benchmark: "S&P Green Bond Select",
    exclusions: ["Fossiles", "Armement"],
  },
  {
    id: "a-wtef",
    ticker: "WTEF",
    name: "Invesco Water Resources",
    category: "ETF",
    description:
      "Entreprises qui gèrent, traitent ou préservent l'eau. Une ressource rare, un investissement essentiel.",
    current_price: 53.2,
    overall_esg_score: 8.4,
    climate_score: 8.0,
    social_score: 9.1,
    governance_score: 8.2,
    tags: ["eau", "infrastructure"],
    co2_factor_per_1k_eur: 0.42,
    energy_factor_per_1k_eur: 90,
    themes: ["eau", "biodiversite"],
    issuer: "Invesco",
    domicile: "Irlande",
    currency: "USD",
    ter_pct: 0.60,
    dividend_policy: "Distribuant",
    dividend_yield_pct: 0.8,
    holdings_count: 38,
    top_holdings: ["Ecolab", "Roper Tech.", "Xylem", "American Water Works", "Veralto"],
    sector_breakdown: [
      { label: "Traitement", pct: 42 },
      { label: "Distribution", pct: 28 },
      { label: "Équipements", pct: 20 },
      { label: "Autres", pct: 10 },
    ],
    geo_breakdown: [
      { label: "USA", pct: 88 },
      { label: "Autres", pct: 12 },
    ],
    risk_level: 5,
    inception_year: 2005,
    benchmark: "Nasdaq OMX US Water",
    exclusions: ["Pétrole & gaz"],
  },
  {
    id: "a-hbio",
    ticker: "HBIO",
    name: "Humankind US Stock",
    category: "Action",
    description:
      "Sélection d'entreprises notées sur leur impact humain : conditions de travail, parité, droits sociaux.",
    current_price: 38.9,
    overall_esg_score: 8.6,
    climate_score: 7.5,
    social_score: 9.5,
    governance_score: 8.7,
    tags: ["humain", "égalité"],
    co2_factor_per_1k_eur: 0.28,
    energy_factor_per_1k_eur: 110,
    themes: ["social", "governance"],
    issuer: "Humankind Investments",
    domicile: "USA",
    currency: "USD",
    ter_pct: 0.11,
    dividend_policy: "Distribuant",
    dividend_yield_pct: 1.5,
    holdings_count: 921,
    top_holdings: ["Microsoft", "Pfizer", "Cisco", "Costco", "Procter & Gamble"],
    sector_breakdown: [
      { label: "Santé", pct: 22 },
      { label: "Tech", pct: 20 },
      { label: "Conso.", pct: 18 },
      { label: "Finance", pct: 14 },
      { label: "Autres", pct: 26 },
    ],
    geo_breakdown: [{ label: "USA", pct: 100 }],
    risk_level: 5,
    inception_year: 2021,
    benchmark: "Humankind US Equity Index",
    exclusions: ["Tabac", "Armement", "Jeux d'argent", "Énergies fossiles"],
  },
  {
    id: "a-vegn",
    ticker: "VEGN",
    name: "US Vegan Climate ETF",
    category: "ETF",
    description:
      "Aucune entreprise liée à l'élevage industriel, aux fossiles ou aux tests animaux. Un jardin sans cruauté.",
    current_price: 31.5,
    overall_esg_score: 9.0,
    climate_score: 9.3,
    social_score: 8.6,
    governance_score: 8.5,
    tags: ["vegan", "éthique"],
    co2_factor_per_1k_eur: 0.95,
    energy_factor_per_1k_eur: 260,
    themes: ["biodiversite", "social"],
    issuer: "Beyond Investing",
    domicile: "USA",
    currency: "USD",
    ter_pct: 0.60,
    dividend_policy: "Distribuant",
    dividend_yield_pct: 1.0,
    holdings_count: 270,
    top_holdings: ["Nvidia", "Apple", "Microsoft", "Tesla", "Adobe"],
    sector_breakdown: [
      { label: "Tech", pct: 38 },
      { label: "Santé", pct: 16 },
      { label: "Finance", pct: 14 },
      { label: "Conso.", pct: 12 },
      { label: "Autres", pct: 20 },
    ],
    geo_breakdown: [{ label: "USA", pct: 100 }],
    risk_level: 5,
    inception_year: 2019,
    benchmark: "Beyond Investing US Climate Index",
    exclusions: ["Élevage", "Tests animaux", "Fossiles", "Armement", "Tabac"],
  },
  {
    id: "a-pscw",
    ticker: "PSCW",
    name: "Patagonia Circular Goods",
    category: "Action",
    description:
      "Entreprise pionnière de la mode durable et circulaire : réparation, recyclage, matériaux régénératifs.",
    current_price: 88.0,
    overall_esg_score: 9.4,
    climate_score: 9.1,
    social_score: 9.5,
    governance_score: 9.6,
    tags: ["circulaire", "mode durable"],
    co2_factor_per_1k_eur: 0.52,
    energy_factor_per_1k_eur: 130,
    themes: ["circulaire", "social"],
    issuer: "Patagonia Inc. (fictif coté)",
    domicile: "USA",
    currency: "USD",
    dividend_policy: "Distribuant",
    dividend_yield_pct: 0.4,
    sector_breakdown: [{ label: "Textile / Outdoor", pct: 100 }],
    geo_breakdown: [
      { label: "USA", pct: 60 },
      { label: "Europe", pct: 25 },
      { label: "Asie", pct: 15 },
    ],
    risk_level: 5,
    inception_year: 1973,
    benchmark: "—",
  },
  {
    id: "a-aqua",
    ticker: "AQUA",
    name: "Evoqua Water Tech",
    category: "Action",
    description:
      "Technologies de purification d'eau pour les villes et les industries. Au cœur des enjeux climatiques.",
    current_price: 47.1,
    overall_esg_score: 8.3,
    climate_score: 8.6,
    social_score: 8.0,
    governance_score: 8.4,
    tags: ["eau", "tech"],
    co2_factor_per_1k_eur: 0.65,
    energy_factor_per_1k_eur: 175,
    themes: ["eau", "tech"],
    issuer: "Evoqua Water Technologies",
    domicile: "USA",
    currency: "USD",
    dividend_policy: "Capitalisant",
    sector_breakdown: [{ label: "Tech. de l'eau", pct: 100 }],
    geo_breakdown: [
      { label: "USA", pct: 75 },
      { label: "Europe", pct: 15 },
      { label: "Asie", pct: 10 },
    ],
    risk_level: 6,
    inception_year: 2017,
    benchmark: "—",
  },
  {
    id: "a-esge",
    ticker: "ESGE",
    name: "iShares MSCI EM ESG Enhanced",
    category: "ETF",
    description:
      "Marchés émergents filtrés ESG : croissance asiatique et latino-américaine, avec exclusions strictes.",
    current_price: 28.4,
    overall_esg_score: 7.9,
    climate_score: 7.6,
    social_score: 8.0,
    governance_score: 7.7,
    tags: ["émergents", "diversifié", "ESG"],
    co2_factor_per_1k_eur: 0.78,
    energy_factor_per_1k_eur: 140,
    themes: ["climat", "social"],
    issuer: "BlackRock iShares",
    domicile: "Irlande",
    currency: "USD",
    ter_pct: 0.18,
    dividend_policy: "Capitalisant",
    holdings_count: 320,
    top_holdings: ["TSMC", "Tencent", "Samsung", "Alibaba", "Infosys"],
    sector_breakdown: [
      { label: "Tech", pct: 28 },
      { label: "Finance", pct: 22 },
      { label: "Conso.", pct: 14 },
      { label: "Industrie", pct: 12 },
      { label: "Autres", pct: 24 },
    ],
    geo_breakdown: [
      { label: "Chine", pct: 28 },
      { label: "Taïwan", pct: 19 },
      { label: "Inde", pct: 17 },
      { label: "Corée", pct: 12 },
      { label: "Autres", pct: 24 },
    ],
    risk_level: 6,
    inception_year: 2018,
    benchmark: "MSCI EM ESG Enhanced",
    exclusions: ["Charbon", "Tabac", "Armes controversées"],
  },
  {
    id: "a-eurx",
    ticker: "EURX",
    name: "Lyxor STOXX Europe 600 ESG",
    category: "ETF",
    description:
      "600 valeurs européennes leaders, filtrées sur des critères de durabilité. Cœur de portefeuille européen.",
    current_price: 67.9,
    overall_esg_score: 8.2,
    climate_score: 7.9,
    social_score: 8.4,
    governance_score: 8.5,
    tags: ["Europe", "ESG", "large cap"],
    co2_factor_per_1k_eur: 0.41,
    energy_factor_per_1k_eur: 165,
    themes: ["climat", "governance"],
    issuer: "Amundi Lyxor",
    domicile: "Luxembourg",
    currency: "EUR",
    ter_pct: 0.15,
    dividend_policy: "Distribuant",
    dividend_yield_pct: 2.6,
    holdings_count: 540,
    top_holdings: ["Novo Nordisk", "ASML", "Nestlé", "LVMH", "SAP"],
    sector_breakdown: [
      { label: "Santé", pct: 18 },
      { label: "Finance", pct: 16 },
      { label: "Industrie", pct: 15 },
      { label: "Conso.", pct: 14 },
      { label: "Tech", pct: 11 },
      { label: "Autres", pct: 26 },
    ],
    geo_breakdown: [
      { label: "France", pct: 18 },
      { label: "Allemagne", pct: 16 },
      { label: "Suisse", pct: 15 },
      { label: "UK", pct: 22 },
      { label: "Autres", pct: 29 },
    ],
    risk_level: 5,
    inception_year: 2018,
    benchmark: "STOXX Europe 600 ESG-X",
    exclusions: ["Armes controversées", "Tabac", "Charbon"],
  },
  {
    id: "a-fors",
    ticker: "FORS",
    name: "iShares Global Timber & Forestry",
    category: "ETF",
    description:
      "Entreprises forestières et papetières certifiées. Capter la valeur du carbone séquestré et du bois durable.",
    current_price: 71.2,
    overall_esg_score: 8.5,
    climate_score: 9.0,
    social_score: 7.8,
    governance_score: 8.2,
    tags: ["forêt", "carbone", "biodiversité"],
    co2_factor_per_1k_eur: 1.4,
    energy_factor_per_1k_eur: 90,
    themes: ["biodiversite", "climat"],
    issuer: "BlackRock iShares",
    domicile: "Irlande",
    currency: "USD",
    ter_pct: 0.65,
    dividend_policy: "Distribuant",
    dividend_yield_pct: 2.1,
    holdings_count: 25,
    top_holdings: ["Weyerhaeuser", "Rayonier", "Mondi", "UPM-Kymmene", "Stora Enso"],
    sector_breakdown: [
      { label: "Sylviculture", pct: 55 },
      { label: "Papier durable", pct: 32 },
      { label: "Emballage", pct: 13 },
    ],
    geo_breakdown: [
      { label: "USA", pct: 48 },
      { label: "Europe", pct: 34 },
      { label: "Asie", pct: 12 },
      { label: "Autres", pct: 6 },
    ],
    risk_level: 5,
    inception_year: 2008,
    benchmark: "S&P Global Timber & Forestry",
    exclusions: ["Déforestation non certifiée"],
  },
  {
    id: "a-soci",
    ticker: "SOCI",
    name: "BNP Paribas Easy Social Bond",
    category: "Obligation",
    description:
      "Obligations sociales : logement abordable, santé, éducation. Le pendant social des green bonds.",
    current_price: 102.3,
    overall_esg_score: 8.9,
    climate_score: 7.6,
    social_score: 9.7,
    governance_score: 9.0,
    tags: ["obligation", "social", "stable"],
    co2_factor_per_1k_eur: 0.22,
    energy_factor_per_1k_eur: 60,
    themes: ["social", "governance"],
    issuer: "BNP Paribas Asset Management",
    domicile: "Luxembourg",
    currency: "EUR",
    ter_pct: 0.25,
    dividend_policy: "Distribuant",
    dividend_yield_pct: 3.1,
    holdings_count: 210,
    top_holdings: ["CADES France", "KfW", "BEI", "Région IdF", "ICO Espagne"],
    sector_breakdown: [
      { label: "Logement", pct: 34 },
      { label: "Santé", pct: 26 },
      { label: "Éducation", pct: 20 },
      { label: "Emploi", pct: 12 },
      { label: "Autres", pct: 8 },
    ],
    geo_breakdown: [
      { label: "Europe", pct: 72 },
      { label: "Multilatéral", pct: 20 },
      { label: "Autres", pct: 8 },
    ],
    risk_level: 3,
    inception_year: 2020,
    benchmark: "Bloomberg MSCI Social Bond",
    exclusions: ["Fossiles", "Armement"],
  },
  {
    id: "a-msc",
    ticker: "MSCI",
    name: "Microsoft Corp.",
    category: "Action",
    description:
      "Cloud, IA et productivité. Engagement carbone négatif d'ici 2030 et alimentation 100 % renouvelable.",
    current_price: 418.5,
    overall_esg_score: 8.4,
    climate_score: 8.6,
    social_score: 8.2,
    governance_score: 8.8,
    tags: ["tech", "cloud", "IA"],
    co2_factor_per_1k_eur: 0.18,
    energy_factor_per_1k_eur: 320,
    themes: ["tech", "climat"],
    issuer: "Microsoft (NASDAQ)",
    domicile: "USA",
    currency: "USD",
    dividend_policy: "Distribuant",
    dividend_yield_pct: 0.7,
    sector_breakdown: [{ label: "Logiciel & cloud", pct: 100 }],
    geo_breakdown: [
      { label: "USA", pct: 50 },
      { label: "International", pct: 50 },
    ],
    risk_level: 5,
    inception_year: 1986,
    benchmark: "—",
  },
  {
    id: "a-nvo",
    ticker: "NVO",
    name: "Novo Nordisk A/S",
    category: "Action",
    description:
      "Leader mondial du traitement du diabète et de l'obésité. Forte intensité de R&D, gouvernance scandinave.",
    current_price: 116.4,
    overall_esg_score: 8.8,
    climate_score: 8.3,
    social_score: 9.2,
    governance_score: 9.0,
    tags: ["santé", "innovation"],
    co2_factor_per_1k_eur: 0.31,
    energy_factor_per_1k_eur: 95,
    themes: ["social", "governance"],
    issuer: "Novo Nordisk (Copenhague)",
    domicile: "Danemark",
    currency: "DKK",
    dividend_policy: "Distribuant",
    dividend_yield_pct: 1.5,
    sector_breakdown: [{ label: "Santé pharmaceutique", pct: 100 }],
    geo_breakdown: [
      { label: "Amérique du Nord", pct: 58 },
      { label: "Europe", pct: 22 },
      { label: "Asie", pct: 14 },
      { label: "Autres", pct: 6 },
    ],
    risk_level: 4,
    inception_year: 1923,
    benchmark: "—",
  },
  {
    id: "a-asml",
    ticker: "ASML",
    name: "ASML Holding",
    category: "Action",
    description:
      "Monopole mondial des machines de lithographie EUV. Pilier de la chaîne semi-conducteur européenne.",
    current_price: 712.8,
    overall_esg_score: 8.3,
    climate_score: 8.1,
    social_score: 8.0,
    governance_score: 8.8,
    tags: ["tech", "Europe", "semi"],
    co2_factor_per_1k_eur: 0.39,
    energy_factor_per_1k_eur: 145,
    themes: ["tech", "governance"],
    issuer: "ASML Holding NV",
    domicile: "Pays-Bas",
    currency: "EUR",
    dividend_policy: "Distribuant",
    dividend_yield_pct: 0.9,
    sector_breakdown: [{ label: "Équipements semi-conducteurs", pct: 100 }],
    geo_breakdown: [
      { label: "Asie", pct: 70 },
      { label: "USA", pct: 18 },
      { label: "Europe", pct: 12 },
    ],
    risk_level: 6,
    inception_year: 1984,
    benchmark: "—",
  },
  {
    id: "a-circ",
    ticker: "CIRC",
    name: "VanEck Circular Economy",
    category: "ETF",
    description:
      "Recyclage, réemploi et matériaux régénératifs. Acteurs purs et industriels qui réinventent leurs chaînes.",
    current_price: 22.9,
    overall_esg_score: 8.7,
    climate_score: 8.8,
    social_score: 8.4,
    governance_score: 8.6,
    tags: ["circulaire", "industrie", "innovation"],
    co2_factor_per_1k_eur: 0.61,
    energy_factor_per_1k_eur: 210,
    themes: ["circulaire", "climat"],
    issuer: "VanEck",
    domicile: "Irlande",
    currency: "EUR",
    ter_pct: 0.40,
    dividend_policy: "Capitalisant",
    holdings_count: 42,
    top_holdings: ["Tomra Systems", "Schneider Electric", "Waste Management", "Veolia", "Smurfit Kappa"],
    sector_breakdown: [
      { label: "Gestion déchets", pct: 38 },
      { label: "Emballage durable", pct: 24 },
      { label: "Réemploi", pct: 22 },
      { label: "Autres", pct: 16 },
    ],
    geo_breakdown: [
      { label: "Europe", pct: 48 },
      { label: "USA", pct: 36 },
      { label: "Asie", pct: 12 },
      { label: "Autres", pct: 4 },
    ],
    risk_level: 5,
    inception_year: 2022,
    benchmark: "MVIS Global Circular Economy",
    exclusions: ["Fossiles", "Plastique vierge"],
  },
  {
    id: "a-h2",
    ticker: "H2EU",
    name: "L&G Hydrogen Economy",
    category: "ETF",
    description:
      "Hydrogène vert : production, stockage, mobilité lourde. Pari sur le vecteur énergétique de demain.",
    current_price: 7.45,
    overall_esg_score: 9.0,
    climate_score: 9.6,
    social_score: 8.0,
    governance_score: 8.3,
    tags: ["hydrogène", "climat", "innovation"],
    co2_factor_per_1k_eur: 1.6,
    energy_factor_per_1k_eur: 520,
    themes: ["climat", "tech"],
    issuer: "Legal & General",
    domicile: "Irlande",
    currency: "USD",
    ter_pct: 0.49,
    dividend_policy: "Capitalisant",
    holdings_count: 28,
    top_holdings: ["Plug Power", "Linde", "Air Products", "Nel ASA", "Ballard Power"],
    sector_breakdown: [
      { label: "Production H₂", pct: 42 },
      { label: "Équipements", pct: 30 },
      { label: "Mobilité", pct: 18 },
      { label: "Autres", pct: 10 },
    ],
    geo_breakdown: [
      { label: "USA", pct: 44 },
      { label: "Europe", pct: 36 },
      { label: "Asie", pct: 18 },
      { label: "Autres", pct: 2 },
    ],
    risk_level: 7,
    inception_year: 2021,
    benchmark: "Solactive Hydrogen Economy",
    exclusions: ["Hydrogène gris", "Fossiles"],
  },
  {
    id: "a-orsta",
    ticker: "ORST",
    name: "Ørsted A/S",
    category: "Action",
    description:
      "Premier opérateur mondial d'éolien offshore. Ancien pétrolier devenu pure player des renouvelables.",
    current_price: 41.6,
    overall_esg_score: 9.3,
    climate_score: 9.8,
    social_score: 8.6,
    governance_score: 9.1,
    tags: ["éolien", "énergie", "Europe"],
    co2_factor_per_1k_eur: 1.8,
    energy_factor_per_1k_eur: 610,
    themes: ["climat", "tech"],
    issuer: "Ørsted (Copenhague)",
    domicile: "Danemark",
    currency: "DKK",
    dividend_policy: "Distribuant",
    dividend_yield_pct: 2.4,
    sector_breakdown: [
      { label: "Éolien offshore", pct: 78 },
      { label: "Éolien onshore", pct: 14 },
      { label: "Solaire & stockage", pct: 8 },
    ],
    geo_breakdown: [
      { label: "Europe", pct: 64 },
      { label: "USA", pct: 22 },
      { label: "Asie", pct: 14 },
    ],
    risk_level: 5,
    inception_year: 1972,
    benchmark: "—",
    exclusions: ["Charbon", "Pétrole"],
  },
  {
    id: "a-schn",
    ticker: "SU",
    name: "Schneider Electric",
    category: "Action",
    description:
      "Gestion intelligente de l'énergie et automatisation. Souvent classée parmi les entreprises les plus durables au monde.",
    current_price: 224.7,
    overall_esg_score: 9.1,
    climate_score: 9.2,
    social_score: 8.9,
    governance_score: 9.2,
    tags: ["énergie", "industrie", "France"],
    co2_factor_per_1k_eur: 0.46,
    energy_factor_per_1k_eur: 260,
    themes: ["climat", "circulaire", "tech"],
    issuer: "Schneider Electric SE",
    domicile: "France",
    currency: "EUR",
    dividend_policy: "Distribuant",
    dividend_yield_pct: 1.7,
    sector_breakdown: [
      { label: "Gestion énergie", pct: 72 },
      { label: "Automatisation", pct: 28 },
    ],
    geo_breakdown: [
      { label: "Amérique du Nord", pct: 32 },
      { label: "Europe", pct: 28 },
      { label: "Asie-Pacifique", pct: 30 },
      { label: "Autres", pct: 10 },
    ],
    risk_level: 5,
    inception_year: 1836,
    benchmark: "—",
  },
  {
    id: "a-reit",
    ticker: "GRET",
    name: "VanEck Sustainable REIT",
    category: "Immobilier",
    description:
      "Immobilier coté certifié bas-carbone : bureaux green-labelled, logistique durable, résidentiel BBCA.",
    current_price: 48.2,
    overall_esg_score: 8.3,
    climate_score: 8.7,
    social_score: 8.0,
    governance_score: 8.2,
    tags: ["immobilier", "rendement"],
    co2_factor_per_1k_eur: 0.55,
    energy_factor_per_1k_eur: 120,
    themes: ["climat", "circulaire"],
    issuer: "VanEck",
    domicile: "Irlande",
    currency: "EUR",
    ter_pct: 0.30,
    dividend_policy: "Distribuant",
    dividend_yield_pct: 4.2,
    holdings_count: 95,
    top_holdings: ["Prologis", "Vonovia", "Klepierre", "Gecina", "Segro"],
    sector_breakdown: [
      { label: "Logistique", pct: 32 },
      { label: "Résidentiel", pct: 28 },
      { label: "Bureaux verts", pct: 22 },
      { label: "Autres", pct: 18 },
    ],
    geo_breakdown: [
      { label: "Europe", pct: 56 },
      { label: "USA", pct: 32 },
      { label: "Asie", pct: 12 },
    ],
    risk_level: 4,
    inception_year: 2021,
    benchmark: "GPR Sustainable REIT",
    exclusions: ["Bâtiments non certifiés"],
  },
];

export const MOCK_HOLDINGS: MockHolding[] = [
  { id: "h1", asset: MOCK_ASSETS[0], allocationPct: 38, performancePct: 6.4, avgBuyPrice: 86.8 },
  { id: "h2", asset: MOCK_ASSETS[1], allocationPct: 24, performancePct: 14.2, avgBuyPrice: 12.96 },
  { id: "h3", asset: MOCK_ASSETS[2], allocationPct: 18, performancePct: 2.1, avgBuyPrice: 24.1 },
  { id: "h4", asset: MOCK_ASSETS[3], allocationPct: 12, performancePct: -3.5, avgBuyPrice: 55.1 },
  { id: "h5", asset: MOCK_ASSETS[6], allocationPct: 8, performancePct: 9.8, avgBuyPrice: 80.1 },
];

export const MOCK_PORTFOLIO = {
  total_value: 4287,
  total_invested: 3950,
  co2_avoided: 1.4, // tonnes
  trees_equivalent: 64,
  energy_financed: 820, // kWh
  overall_score: 8.6,
};

export const MOCK_WALLET = { balance: 312, currency: "EUR" };

export const MOCK_USER_NAME = "Sofia";

export const MOCK_TRANSACTIONS: MockTransaction[] = [
  { id: "t1", created_at: "2025-04-12T08:00:00Z", type: "buy", asset_ticker: "CLEAN", asset_name: "iShares Global Clean Energy", amount: 200 },
  { id: "t2", created_at: "2025-04-02T08:00:00Z", type: "deposit", asset_ticker: null, asset_name: null, amount: 250 },
  { id: "t3", created_at: "2025-03-22T08:00:00Z", type: "buy", asset_ticker: "WTEF", asset_name: "Invesco Water Resources", amount: 350 },
  { id: "t4", created_at: "2025-03-05T08:00:00Z", type: "buy", asset_ticker: "PSCW", asset_name: "Patagonia Circular Goods", amount: 320 },
  { id: "t5", created_at: "2025-02-15T08:00:00Z", type: "deposit", asset_ticker: null, asset_name: null, amount: 500 },
  { id: "t6", created_at: "2025-02-04T08:00:00Z", type: "buy", asset_ticker: "GRNB", asset_name: "VanEck Green Bond", amount: 600 },
  { id: "t7", created_at: "2025-01-18T08:00:00Z", type: "buy", asset_ticker: "IWRD", asset_name: "iShares Core MSCI World", amount: 1500 },
  { id: "t8", created_at: "2025-01-05T08:00:00Z", type: "deposit", asset_ticker: null, asset_name: null, amount: 2000 },
];

export const MOCK_BADGES = [
  { id: "first_seed", name: "Premier investissement", description: "Tu as effectué ton premier investissement.", icon: "🌱", tier: "bronze" as const, unlocked: true },
  { id: "patient_gardener", name: "Investisseur patient", description: "90 jours sans paniquer.", icon: "🧘", tier: "bronze" as const, unlocked: true },
  { id: "biodiversity", name: "Bien diversifié", description: "5 actifs différents en portefeuille.", icon: "🌿", tier: "silver" as const, unlocked: true },
  { id: "regular_waterer", name: "Versements réguliers", description: "6 mois de versements consécutifs.", icon: "💧", tier: "silver" as const, unlocked: false },
  { id: "carbon_neutral", name: "Empreinte nulle", description: "Autant de CO₂ évité que ta conso annuelle.", icon: "🌍", tier: "silver" as const, unlocked: false },
  { id: "forest", name: "Petite forêt", description: "100 arbres équivalents financés.", icon: "🌳", tier: "gold" as const, unlocked: false },
  { id: "first_harvest", name: "Premier retrait", description: "Tu as retiré pour un projet qui te tient à cœur.", icon: "🍎", tier: "gold" as const, unlocked: false },
  { id: "aligned", name: "Parfait alignement", description: "ESG > 8,5 sur tout.", icon: "✨", tier: "gold" as const, unlocked: true },
];
