/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReglagesRouteImport } from './routes/reglages'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MethodologieRouteImport } from './routes/methodologie'
import { Route as EthiRouteImport } from './routes/ethi'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComparatifRouteImport } from './routes/comparatif'
import { Route as CertificatRouteImport } from './routes/certificat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksRefreshMarketDataRouteImport } from './routes/hooks/refresh-market-data'
import { Route as ApiEthiRouteImport } from './routes/api.ethi'

const ReglagesRoute = ReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologieRoute = MethodologieRouteImport.update({
  id: '/methodologie',
  path: '/methodologie',
  getParentRoute: () => rootRouteImport,
} as any)
const EthiRoute = EthiRouteImport.update({
  id: '/ethi',
  path: '/ethi',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparatifRoute = ComparatifRouteImport.update({
  id: '/comparatif',
  path: '/comparatif',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatRoute = CertificatRouteImport.update({
  id: '/certificat',
  path: '/certificat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksRefreshMarketDataRoute = HooksRefreshMarketDataRouteImport.update({
  id: '/hooks/refresh-market-data',
  path: '/hooks/refresh-market-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEthiRoute = ApiEthiRouteImport.update({
  id: '/api/ethi',
  path: '/api/ethi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/certificat': typeof CertificatRoute
  '/comparatif': typeof ComparatifRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/ethi': typeof EthiRoute
  '/methodologie': typeof MethodologieRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/profil': typeof ProfilRoute
  '/reglages': typeof ReglagesRoute
  '/api/ethi': typeof ApiEthiRoute
  '/hooks/refresh-market-data': typeof HooksRefreshMarketDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/certificat': typeof CertificatRoute
  '/comparatif': typeof ComparatifRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/ethi': typeof EthiRoute
  '/methodologie': typeof MethodologieRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/profil': typeof ProfilRoute
  '/reglages': typeof ReglagesRoute
  '/api/ethi': typeof ApiEthiRoute
  '/hooks/refresh-market-data': typeof HooksRefreshMarketDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/certificat': typeof CertificatRoute
  '/comparatif': typeof ComparatifRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/ethi': typeof EthiRoute
  '/methodologie': typeof MethodologieRoute
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/profil': typeof ProfilRoute
  '/reglages': typeof ReglagesRoute
  '/api/ethi': typeof ApiEthiRoute
  '/hooks/refresh-market-data': typeof HooksRefreshMarketDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/certificat'
    | '/comparatif'
    | '/dashboard'
    | '/discover'
    | '/ethi'
    | '/methodologie'
    | '/onboarding'
    | '/portfolio'
    | '/profil'
    | '/reglages'
    | '/api/ethi'
    | '/hooks/refresh-market-data'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/certificat'
    | '/comparatif'
    | '/dashboard'
    | '/discover'
    | '/ethi'
    | '/methodologie'
    | '/onboarding'
    | '/portfolio'
    | '/profil'
    | '/reglages'
    | '/api/ethi'
    | '/hooks/refresh-market-data'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/certificat'
    | '/comparatif'
    | '/dashboard'
    | '/discover'
    | '/ethi'
    | '/methodologie'
    | '/onboarding'
    | '/portfolio'
    | '/profil'
    | '/reglages'
    | '/api/ethi'
    | '/hooks/refresh-market-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CertificatRoute: typeof CertificatRoute
  ComparatifRoute: typeof ComparatifRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  EthiRoute: typeof EthiRoute
  MethodologieRoute: typeof MethodologieRoute
  OnboardingRoute: typeof OnboardingRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfilRoute: typeof ProfilRoute
  ReglagesRoute: typeof ReglagesRoute
  ApiEthiRoute: typeof ApiEthiRoute
  HooksRefreshMarketDataRoute: typeof HooksRefreshMarketDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reglages': {
      id: '/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof ReglagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodologie': {
      id: '/methodologie'
      path: '/methodologie'
      fullPath: '/methodologie'
      preLoaderRoute: typeof MethodologieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethi': {
      id: '/ethi'
      path: '/ethi'
      fullPath: '/ethi'
      preLoaderRoute: typeof EthiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparatif': {
      id: '/comparatif'
      path: '/comparatif'
      fullPath: '/comparatif'
      preLoaderRoute: typeof ComparatifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificat': {
      id: '/certificat'
      path: '/certificat'
      fullPath: '/certificat'
      preLoaderRoute: typeof CertificatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/refresh-market-data': {
      id: '/hooks/refresh-market-data'
      path: '/hooks/refresh-market-data'
      fullPath: '/hooks/refresh-market-data'
      preLoaderRoute: typeof HooksRefreshMarketDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ethi': {
      id: '/api/ethi'
      path: '/api/ethi'
      fullPath: '/api/ethi'
      preLoaderRoute: typeof ApiEthiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CertificatRoute: CertificatRoute,
  ComparatifRoute: ComparatifRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  EthiRoute: EthiRoute,
  MethodologieRoute: MethodologieRoute,
  OnboardingRoute: OnboardingRoute,
  PortfolioRoute: PortfolioRoute,
  ProfilRoute: ProfilRoute,
  ReglagesRoute: ReglagesRoute,
  ApiEthiRoute: ApiEthiRoute,
  HooksRefreshMarketDataRoute: HooksRefreshMarketDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
