/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WrappedRouteImport } from './routes/wrapped'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as ReveilRouteImport } from './routes/reveil'
import { Route as ReglagesRouteImport } from './routes/reglages'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ObjectifsRouteImport } from './routes/objectifs'
import { Route as MethodologieRouteImport } from './routes/methodologie'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LeFilRouteImport } from './routes/le-fil'
import { Route as EthiRouteImport } from './routes/ethi'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursRouteImport } from './routes/cours'
import { Route as ConstruireRouteImport } from './routes/construire'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ComprendreRouteImport } from './routes/comprendre'
import { Route as ComparatifRouteImport } from './routes/comparatif'
import { Route as CommunauteRouteImport } from './routes/communaute'
import { Route as CguRouteImport } from './routes/cgu'
import { Route as CertificatRouteImport } from './routes/certificat'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursIndexRouteImport } from './routes/cours.index'
import { Route as VoteResolutionIdRouteImport } from './routes/vote.$resolutionId'
import { Route as ObjectifsGoalIdRouteImport } from './routes/objectifs.$goalId'
import { Route as HooksRefreshMarketDataRouteImport } from './routes/hooks/refresh-market-data'
import { Route as HooksRecomputeRiskModelRouteImport } from './routes/hooks/recompute-risk-model'
import { Route as HooksRecomputeIngestionPlanRouteImport } from './routes/hooks/recompute-ingestion-plan'
import { Route as HooksDispatchNotificationsRouteImport } from './routes/hooks/dispatch-notifications'
import { Route as CoursSlugRouteImport } from './routes/cours.$slug'
import { Route as ApiEthiRouteImport } from './routes/api.ethi'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicEsgPreviewRouteImport } from './routes/api.public.esg-preview'
import { Route as AuthenticatedAdminDataRouteImport } from './routes/_authenticated/admin.data'
import { Route as AuthenticatedAdminBetaRouteImport } from './routes/_authenticated/admin.beta'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const WrappedRoute = WrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const ReveilRoute = ReveilRouteImport.update({
  id: '/reveil',
  path: '/reveil',
  getParentRoute: () => rootRouteImport,
} as any)
const ReglagesRoute = ReglagesRouteImport.update({
  id: '/reglages',
  path: '/reglages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectifsRoute = ObjectifsRouteImport.update({
  id: '/objectifs',
  path: '/objectifs',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologieRoute = MethodologieRouteImport.update({
  id: '/methodologie',
  path: '/methodologie',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LeFilRoute = LeFilRouteImport.update({
  id: '/le-fil',
  path: '/le-fil',
  getParentRoute: () => rootRouteImport,
} as any)
const EthiRoute = EthiRouteImport.update({
  id: '/ethi',
  path: '/ethi',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursRoute = CoursRouteImport.update({
  id: '/cours',
  path: '/cours',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstruireRoute = ConstruireRouteImport.update({
  id: '/construire',
  path: '/construire',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprendreRoute = ComprendreRouteImport.update({
  id: '/comprendre',
  path: '/comprendre',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparatifRoute = ComparatifRouteImport.update({
  id: '/comparatif',
  path: '/comparatif',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunauteRoute = CommunauteRouteImport.update({
  id: '/communaute',
  path: '/communaute',
  getParentRoute: () => rootRouteImport,
} as any)
const CguRoute = CguRouteImport.update({
  id: '/cgu',
  path: '/cgu',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatRoute = CertificatRouteImport.update({
  id: '/certificat',
  path: '/certificat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursIndexRoute = CoursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursRoute,
} as any)
const VoteResolutionIdRoute = VoteResolutionIdRouteImport.update({
  id: '/$resolutionId',
  path: '/$resolutionId',
  getParentRoute: () => VoteRoute,
} as any)
const ObjectifsGoalIdRoute = ObjectifsGoalIdRouteImport.update({
  id: '/$goalId',
  path: '/$goalId',
  getParentRoute: () => ObjectifsRoute,
} as any)
const HooksRefreshMarketDataRoute = HooksRefreshMarketDataRouteImport.update({
  id: '/hooks/refresh-market-data',
  path: '/hooks/refresh-market-data',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksRecomputeRiskModelRoute = HooksRecomputeRiskModelRouteImport.update({
  id: '/hooks/recompute-risk-model',
  path: '/hooks/recompute-risk-model',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksRecomputeIngestionPlanRoute =
  HooksRecomputeIngestionPlanRouteImport.update({
    id: '/hooks/recompute-ingestion-plan',
    path: '/hooks/recompute-ingestion-plan',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksDispatchNotificationsRoute =
  HooksDispatchNotificationsRouteImport.update({
    id: '/hooks/dispatch-notifications',
    path: '/hooks/dispatch-notifications',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursSlugRoute = CoursSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursRoute,
} as any)
const ApiEthiRoute = ApiEthiRouteImport.update({
  id: '/api/ethi',
  path: '/api/ethi',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEsgPreviewRoute = ApiPublicEsgPreviewRouteImport.update({
  id: '/api/public/esg-preview',
  path: '/api/public/esg-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminDataRoute = AuthenticatedAdminDataRouteImport.update({
  id: '/admin/data',
  path: '/admin/data',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminBetaRoute = AuthenticatedAdminBetaRouteImport.update({
  id: '/admin/beta',
  path: '/admin/beta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/certificat': typeof CertificatRoute
  '/cgu': typeof CguRoute
  '/communaute': typeof CommunauteRoute
  '/comparatif': typeof ComparatifRoute
  '/comprendre': typeof ComprendreRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/construire': typeof ConstruireRoute
  '/cours': typeof CoursRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/ethi': typeof EthiRoute
  '/le-fil': typeof LeFilRoute
  '/mcp': typeof McpRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/methodologie': typeof MethodologieRoute
  '/objectifs': typeof ObjectifsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/profil': typeof ProfilRoute
  '/reglages': typeof ReglagesRoute
  '/reveil': typeof ReveilRoute
  '/tarifs': typeof TarifsRoute
  '/vote': typeof VoteRouteWithChildren
  '/waitlist': typeof WaitlistRoute
  '/wrapped': typeof WrappedRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/ethi': typeof ApiEthiRoute
  '/cours/$slug': typeof CoursSlugRoute
  '/hooks/dispatch-notifications': typeof HooksDispatchNotificationsRoute
  '/hooks/recompute-ingestion-plan': typeof HooksRecomputeIngestionPlanRoute
  '/hooks/recompute-risk-model': typeof HooksRecomputeRiskModelRoute
  '/hooks/refresh-market-data': typeof HooksRefreshMarketDataRoute
  '/objectifs/$goalId': typeof ObjectifsGoalIdRoute
  '/vote/$resolutionId': typeof VoteResolutionIdRoute
  '/cours/': typeof CoursIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/beta': typeof AuthenticatedAdminBetaRoute
  '/admin/data': typeof AuthenticatedAdminDataRoute
  '/api/public/esg-preview': typeof ApiPublicEsgPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/certificat': typeof CertificatRoute
  '/cgu': typeof CguRoute
  '/communaute': typeof CommunauteRoute
  '/comparatif': typeof ComparatifRoute
  '/comprendre': typeof ComprendreRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/construire': typeof ConstruireRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/ethi': typeof EthiRoute
  '/le-fil': typeof LeFilRoute
  '/mcp': typeof McpRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/methodologie': typeof MethodologieRoute
  '/objectifs': typeof ObjectifsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/profil': typeof ProfilRoute
  '/reglages': typeof ReglagesRoute
  '/reveil': typeof ReveilRoute
  '/tarifs': typeof TarifsRoute
  '/vote': typeof VoteRouteWithChildren
  '/waitlist': typeof WaitlistRoute
  '/wrapped': typeof WrappedRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/ethi': typeof ApiEthiRoute
  '/cours/$slug': typeof CoursSlugRoute
  '/hooks/dispatch-notifications': typeof HooksDispatchNotificationsRoute
  '/hooks/recompute-ingestion-plan': typeof HooksRecomputeIngestionPlanRoute
  '/hooks/recompute-risk-model': typeof HooksRecomputeRiskModelRoute
  '/hooks/refresh-market-data': typeof HooksRefreshMarketDataRoute
  '/objectifs/$goalId': typeof ObjectifsGoalIdRoute
  '/vote/$resolutionId': typeof VoteResolutionIdRoute
  '/cours': typeof CoursIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/beta': typeof AuthenticatedAdminBetaRoute
  '/admin/data': typeof AuthenticatedAdminDataRoute
  '/api/public/esg-preview': typeof ApiPublicEsgPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/certificat': typeof CertificatRoute
  '/cgu': typeof CguRoute
  '/communaute': typeof CommunauteRoute
  '/comparatif': typeof ComparatifRoute
  '/comprendre': typeof ComprendreRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/construire': typeof ConstruireRoute
  '/cours': typeof CoursRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/ethi': typeof EthiRoute
  '/le-fil': typeof LeFilRoute
  '/mcp': typeof McpRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/methodologie': typeof MethodologieRoute
  '/objectifs': typeof ObjectifsRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/portfolio': typeof PortfolioRoute
  '/profil': typeof ProfilRoute
  '/reglages': typeof ReglagesRoute
  '/reveil': typeof ReveilRoute
  '/tarifs': typeof TarifsRoute
  '/vote': typeof VoteRouteWithChildren
  '/waitlist': typeof WaitlistRoute
  '/wrapped': typeof WrappedRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/ethi': typeof ApiEthiRoute
  '/cours/$slug': typeof CoursSlugRoute
  '/hooks/dispatch-notifications': typeof HooksDispatchNotificationsRoute
  '/hooks/recompute-ingestion-plan': typeof HooksRecomputeIngestionPlanRoute
  '/hooks/recompute-risk-model': typeof HooksRecomputeRiskModelRoute
  '/hooks/refresh-market-data': typeof HooksRefreshMarketDataRoute
  '/objectifs/$goalId': typeof ObjectifsGoalIdRoute
  '/vote/$resolutionId': typeof VoteResolutionIdRoute
  '/cours/': typeof CoursIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/beta': typeof AuthenticatedAdminBetaRoute
  '/_authenticated/admin/data': typeof AuthenticatedAdminDataRoute
  '/api/public/esg-preview': typeof ApiPublicEsgPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aide'
    | '/auth'
    | '/certificat'
    | '/cgu'
    | '/communaute'
    | '/comparatif'
    | '/comprendre'
    | '/confidentialite'
    | '/construire'
    | '/cours'
    | '/dashboard'
    | '/discover'
    | '/ethi'
    | '/le-fil'
    | '/mcp'
    | '/mentions-legales'
    | '/methodologie'
    | '/objectifs'
    | '/onboarding'
    | '/portfolio'
    | '/profil'
    | '/reglages'
    | '/reveil'
    | '/tarifs'
    | '/vote'
    | '/waitlist'
    | '/wrapped'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/ethi'
    | '/cours/$slug'
    | '/hooks/dispatch-notifications'
    | '/hooks/recompute-ingestion-plan'
    | '/hooks/recompute-risk-model'
    | '/hooks/refresh-market-data'
    | '/objectifs/$goalId'
    | '/vote/$resolutionId'
    | '/cours/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/beta'
    | '/admin/data'
    | '/api/public/esg-preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aide'
    | '/auth'
    | '/certificat'
    | '/cgu'
    | '/communaute'
    | '/comparatif'
    | '/comprendre'
    | '/confidentialite'
    | '/construire'
    | '/dashboard'
    | '/discover'
    | '/ethi'
    | '/le-fil'
    | '/mcp'
    | '/mentions-legales'
    | '/methodologie'
    | '/objectifs'
    | '/onboarding'
    | '/portfolio'
    | '/profil'
    | '/reglages'
    | '/reveil'
    | '/tarifs'
    | '/vote'
    | '/waitlist'
    | '/wrapped'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/ethi'
    | '/cours/$slug'
    | '/hooks/dispatch-notifications'
    | '/hooks/recompute-ingestion-plan'
    | '/hooks/recompute-risk-model'
    | '/hooks/refresh-market-data'
    | '/objectifs/$goalId'
    | '/vote/$resolutionId'
    | '/cours'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/beta'
    | '/admin/data'
    | '/api/public/esg-preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aide'
    | '/auth'
    | '/certificat'
    | '/cgu'
    | '/communaute'
    | '/comparatif'
    | '/comprendre'
    | '/confidentialite'
    | '/construire'
    | '/cours'
    | '/dashboard'
    | '/discover'
    | '/ethi'
    | '/le-fil'
    | '/mcp'
    | '/mentions-legales'
    | '/methodologie'
    | '/objectifs'
    | '/onboarding'
    | '/portfolio'
    | '/profil'
    | '/reglages'
    | '/reveil'
    | '/tarifs'
    | '/vote'
    | '/waitlist'
    | '/wrapped'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/ethi'
    | '/cours/$slug'
    | '/hooks/dispatch-notifications'
    | '/hooks/recompute-ingestion-plan'
    | '/hooks/recompute-risk-model'
    | '/hooks/refresh-market-data'
    | '/objectifs/$goalId'
    | '/vote/$resolutionId'
    | '/cours/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/beta'
    | '/_authenticated/admin/data'
    | '/api/public/esg-preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AideRoute: typeof AideRoute
  AuthRoute: typeof AuthRoute
  CertificatRoute: typeof CertificatRoute
  CguRoute: typeof CguRoute
  CommunauteRoute: typeof CommunauteRoute
  ComparatifRoute: typeof ComparatifRoute
  ComprendreRoute: typeof ComprendreRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ConstruireRoute: typeof ConstruireRoute
  CoursRoute: typeof CoursRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  EthiRoute: typeof EthiRoute
  LeFilRoute: typeof LeFilRoute
  McpRoute: typeof McpRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MethodologieRoute: typeof MethodologieRoute
  ObjectifsRoute: typeof ObjectifsRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PortfolioRoute: typeof PortfolioRoute
  ProfilRoute: typeof ProfilRoute
  ReglagesRoute: typeof ReglagesRoute
  ReveilRoute: typeof ReveilRoute
  TarifsRoute: typeof TarifsRoute
  VoteRoute: typeof VoteRouteWithChildren
  WaitlistRoute: typeof WaitlistRoute
  WrappedRoute: typeof WrappedRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiEthiRoute: typeof ApiEthiRoute
  HooksDispatchNotificationsRoute: typeof HooksDispatchNotificationsRoute
  HooksRecomputeIngestionPlanRoute: typeof HooksRecomputeIngestionPlanRoute
  HooksRecomputeRiskModelRoute: typeof HooksRecomputeRiskModelRoute
  HooksRefreshMarketDataRoute: typeof HooksRefreshMarketDataRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicEsgPreviewRoute: typeof ApiPublicEsgPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wrapped': {
      id: '/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof WrappedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reveil': {
      id: '/reveil'
      path: '/reveil'
      fullPath: '/reveil'
      preLoaderRoute: typeof ReveilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reglages': {
      id: '/reglages'
      path: '/reglages'
      fullPath: '/reglages'
      preLoaderRoute: typeof ReglagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objectifs': {
      id: '/objectifs'
      path: '/objectifs'
      fullPath: '/objectifs'
      preLoaderRoute: typeof ObjectifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodologie': {
      id: '/methodologie'
      path: '/methodologie'
      fullPath: '/methodologie'
      preLoaderRoute: typeof MethodologieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/le-fil': {
      id: '/le-fil'
      path: '/le-fil'
      fullPath: '/le-fil'
      preLoaderRoute: typeof LeFilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ethi': {
      id: '/ethi'
      path: '/ethi'
      fullPath: '/ethi'
      preLoaderRoute: typeof EthiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours': {
      id: '/cours'
      path: '/cours'
      fullPath: '/cours'
      preLoaderRoute: typeof CoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construire': {
      id: '/construire'
      path: '/construire'
      fullPath: '/construire'
      preLoaderRoute: typeof ConstruireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comprendre': {
      id: '/comprendre'
      path: '/comprendre'
      fullPath: '/comprendre'
      preLoaderRoute: typeof ComprendreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparatif': {
      id: '/comparatif'
      path: '/comparatif'
      fullPath: '/comparatif'
      preLoaderRoute: typeof ComparatifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communaute': {
      id: '/communaute'
      path: '/communaute'
      fullPath: '/communaute'
      preLoaderRoute: typeof CommunauteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cgu': {
      id: '/cgu'
      path: '/cgu'
      fullPath: '/cgu'
      preLoaderRoute: typeof CguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificat': {
      id: '/certificat'
      path: '/certificat'
      fullPath: '/certificat'
      preLoaderRoute: typeof CertificatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours/': {
      id: '/cours/'
      path: '/'
      fullPath: '/cours/'
      preLoaderRoute: typeof CoursIndexRouteImport
      parentRoute: typeof CoursRoute
    }
    '/vote/$resolutionId': {
      id: '/vote/$resolutionId'
      path: '/$resolutionId'
      fullPath: '/vote/$resolutionId'
      preLoaderRoute: typeof VoteResolutionIdRouteImport
      parentRoute: typeof VoteRoute
    }
    '/objectifs/$goalId': {
      id: '/objectifs/$goalId'
      path: '/$goalId'
      fullPath: '/objectifs/$goalId'
      preLoaderRoute: typeof ObjectifsGoalIdRouteImport
      parentRoute: typeof ObjectifsRoute
    }
    '/hooks/refresh-market-data': {
      id: '/hooks/refresh-market-data'
      path: '/hooks/refresh-market-data'
      fullPath: '/hooks/refresh-market-data'
      preLoaderRoute: typeof HooksRefreshMarketDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/recompute-risk-model': {
      id: '/hooks/recompute-risk-model'
      path: '/hooks/recompute-risk-model'
      fullPath: '/hooks/recompute-risk-model'
      preLoaderRoute: typeof HooksRecomputeRiskModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/recompute-ingestion-plan': {
      id: '/hooks/recompute-ingestion-plan'
      path: '/hooks/recompute-ingestion-plan'
      fullPath: '/hooks/recompute-ingestion-plan'
      preLoaderRoute: typeof HooksRecomputeIngestionPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/dispatch-notifications': {
      id: '/hooks/dispatch-notifications'
      path: '/hooks/dispatch-notifications'
      fullPath: '/hooks/dispatch-notifications'
      preLoaderRoute: typeof HooksDispatchNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours/$slug': {
      id: '/cours/$slug'
      path: '/$slug'
      fullPath: '/cours/$slug'
      preLoaderRoute: typeof CoursSlugRouteImport
      parentRoute: typeof CoursRoute
    }
    '/api/ethi': {
      id: '/api/ethi'
      path: '/api/ethi'
      fullPath: '/api/ethi'
      preLoaderRoute: typeof ApiEthiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/esg-preview': {
      id: '/api/public/esg-preview'
      path: '/api/public/esg-preview'
      fullPath: '/api/public/esg-preview'
      preLoaderRoute: typeof ApiPublicEsgPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/data': {
      id: '/_authenticated/admin/data'
      path: '/admin/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AuthenticatedAdminDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/beta': {
      id: '/_authenticated/admin/beta'
      path: '/admin/beta'
      fullPath: '/admin/beta'
      preLoaderRoute: typeof AuthenticatedAdminBetaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminBetaRoute: typeof AuthenticatedAdminBetaRoute
  AuthenticatedAdminDataRoute: typeof AuthenticatedAdminDataRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminBetaRoute: AuthenticatedAdminBetaRoute,
  AuthenticatedAdminDataRoute: AuthenticatedAdminDataRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CoursRouteChildren {
  CoursSlugRoute: typeof CoursSlugRoute
  CoursIndexRoute: typeof CoursIndexRoute
}

const CoursRouteChildren: CoursRouteChildren = {
  CoursSlugRoute: CoursSlugRoute,
  CoursIndexRoute: CoursIndexRoute,
}

const CoursRouteWithChildren = CoursRoute._addFileChildren(CoursRouteChildren)

interface ObjectifsRouteChildren {
  ObjectifsGoalIdRoute: typeof ObjectifsGoalIdRoute
}

const ObjectifsRouteChildren: ObjectifsRouteChildren = {
  ObjectifsGoalIdRoute: ObjectifsGoalIdRoute,
}

const ObjectifsRouteWithChildren = ObjectifsRoute._addFileChildren(
  ObjectifsRouteChildren,
)

interface VoteRouteChildren {
  VoteResolutionIdRoute: typeof VoteResolutionIdRoute
}

const VoteRouteChildren: VoteRouteChildren = {
  VoteResolutionIdRoute: VoteResolutionIdRoute,
}

const VoteRouteWithChildren = VoteRoute._addFileChildren(VoteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AideRoute: AideRoute,
  AuthRoute: AuthRoute,
  CertificatRoute: CertificatRoute,
  CguRoute: CguRoute,
  CommunauteRoute: CommunauteRoute,
  ComparatifRoute: ComparatifRoute,
  ComprendreRoute: ComprendreRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ConstruireRoute: ConstruireRoute,
  CoursRoute: CoursRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  EthiRoute: EthiRoute,
  LeFilRoute: LeFilRoute,
  McpRoute: McpRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MethodologieRoute: MethodologieRoute,
  ObjectifsRoute: ObjectifsRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PortfolioRoute: PortfolioRoute,
  ProfilRoute: ProfilRoute,
  ReglagesRoute: ReglagesRoute,
  ReveilRoute: ReveilRoute,
  TarifsRoute: TarifsRoute,
  VoteRoute: VoteRouteWithChildren,
  WaitlistRoute: WaitlistRoute,
  WrappedRoute: WrappedRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiEthiRoute: ApiEthiRoute,
  HooksDispatchNotificationsRoute: HooksDispatchNotificationsRoute,
  HooksRecomputeIngestionPlanRoute: HooksRecomputeIngestionPlanRoute,
  HooksRecomputeRiskModelRoute: HooksRecomputeRiskModelRoute,
  HooksRefreshMarketDataRoute: HooksRefreshMarketDataRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicEsgPreviewRoute: ApiPublicEsgPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
